# import = [ "~/.config/alacritty/themes/themes/iterm.toml" ]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

startup_mode = "Maximized"

decorations = "full"

opacity = 0.95
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 16

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = '0x666666'
red = '0xff3334'
green = '0x9ec400'
yellow = '0xe7c547'
blue = '0x7aa6da'
magenta = '0xb77ee0'
cyan = '0x54ced6'
white = '0xffffff'

[colors.cursor]
cursor = "0xF5E0DC"
text = "0x1E1D2F"

[colors.normal]
black = '0x000000'
red = '0xd54e53'
green = '0xb9ca4a'
yellow = '0xe6c547'
blue = '0x7aa6da'
magenta = '0xc397d8'
cyan = '0x70c0ba'
white = '0xeaeaea'

[colors.primary]
background = '0x000000'
foreground = '0xeaeaea'

[cursor]
style.shape = "block"
# style.blinking = "off"

[keyboard]
bindings = [
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left", mods = "Alt", chars = "\u001BB" }
]
